config/routes.rb
Rails.application.routes.draw do

	resources :users do
	  resources :shares do
	  		collection do
	    		match 'search' => 'shares#search', via: [:get, :post], as: :search
	  		end
		end
	end	
 end

app/models/equity.rb
class Equity < ActiveRecord::Base
validates 	:code, :name, :presence => true
end

app/models/share.rb
class Share < ActiveRecord::Base
	belongs_to :user
	validates 	:scrip_name, :transaction_date,:buy_sell, :presence => true
	validates 	:quantity,:rate,:brokerage, :presence => true, numericality: true	
	#validates 	:scrip_name , :presence => true,
				#:length => { :maximum =>255},
				#:uniqueness => true

	scope :sorted, lambda { order("shares.id ASC") }
	scope :unique_by_buy_sell, lambda { select('DISTINCT(buy_sell)') }
	scope :unique_by_transaction_date, lambda { select('DISTINCT(transaction_date)') }
	scope :unique_by_scrip_name, lambda { select('DISTINCT(scrip_name)') }
	scope :unique_by_quantity, lambda { select('DISTINCT(quantity)') }
	scope :unique_by_rate, lambda { select('DISTINCT(rate)') }
	scope :unique_by_user_id, lambda { select('DISTINCT(user_id)') }
end

app/models/user.rb
class User < ActiveRecord::Base
	
	has_secure_password

	has_many :shares
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/equitys_controller.rb
class EquitysController < ApplicationController
=begin

	require 'json'


	def index
		@equitys = Equity.all
		@equitys_m =@equitys.pluck(:code, :name)
		respond_to do |format|
			format.html 
			format.json {render json: JSON.parse(@equitys_m)}
		end
		
	end

	
private
  def equity_params
     	params.require(:equity).permit(:name, :code)
  end
=end

end

app/controllers/shares_controller.rb
class SharesController < ApplicationController


layout "admin"

  def search
   
    index    
    render :index
  end

  def index
    
    @q = Share.ransack(params[:q])
    @shares = @q.result(distinct: true)
    
  end
  
  
  def new
  	@share = Share.new()
    @equitys = Equity.order('code asc').all    
  end

  def create
    @share = Share.new(share_params)
     if @share.save 
  		flash[:notice]= "Transaction details saved successfully"
  		redirect_to(shares_path)
  	else
      @equitys = Equity.order('code asc').all
      render(new_share_path)
  	end
  end

  def edit
  	@share = Share.find(params[:id])
    @equitys = Equity.order('code asc').all
  end

  def update
  	@share = Share.find(params[:id])
    	if @share.update_attributes(share_params)
  			flash[:notice]= "Transection details updated successfully"
  			redirect_to(shares_path)
  		else
  			render(edit_share_path(:id))
  		end
  end

  
  def destroy

  	share = Share.find(params[:id]).destroy
  	flash[:notice]=" Transaction on '#{share.scrip_name}' dated '#{share.transaction_date}' destroy successfully"
  	 
    redirect_to(shares_path)
  end


private
  def share_params
     	params.require(:share).permit(:scrip_name, :transaction_date, :buy_sell, :quantity, :rate, :brokerage, :net_rate, :net_value, :bank_balance, :demat_balance, :user_name )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

layout "admin"

def index
	@users = User.order("user_name asc").all
end

def show
	@user = User.find(params[:id])
end

def new

end

def create

end

def edit

end

def update

end

def destroy

end


end

app/helpers/application_helper.rb
module ApplicationHelper
def error_messages_for(object)
	render(:partial => 'application/error_messages', :locals => {:object => object})
end

end

app/helpers/equitys_helper.rb
module EquitysHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_error_messages.html.erb
<% if object  && object.errors.size > 0 %>
	<div id="errorExplanation">
		<h2><%= pluralize(object.errors.size, "error") %> prohibited this record for being saved </h2>
		<p> There were problems with the following fields: </p>
			<ul>
				<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
	</div>
<% end %>

app/views/equitys/index.html.erb
# <%= @equitys_m.as_json %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
	<head>

		<title>PortfolioManagement|Share|| "User" %></title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>  		
  <%= csrf_meta_tags %>
	</head>
	<body>
		<div id="header">
			<h1> Share Transaction Management</h1>
		</div>		
		<div id="main">
			<% if !flash[:notice].blank? %>
 				<div class="notice">
    			<%= flash[:notice] %>
  				</div>
  			<% end %>
			<div id="content">
			<%= yield %>
			</div>
		</div>
		<div id="footer">
		<p id="Copyright">&copy; https://www.sandip.com / Sandip Bhowmick </p>
		</div>
	</body>
</html>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PortfolioManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shares/_form.html.erb
<%= error_messages_for(@share) %>

<table summary="Share form fields">
	<tr>
		<th><%= f.label(:scrip_name, "Script Name")%></th>
		<td><%= f.select(:scrip_name, @equitys.pluck(:name,:code),{prompt: 'Please select'}, id: "js-scrip-name")%></td>
	</tr>
	<tr>
		<th><%= f.label(:transaction_date, "Transaction Date")%></th>
		<td><%= f.date_field(:transaction_date, min: Date.today - 365.days, :value => Date.today) %></td>
	</tr>	
	<tr>
        <th><%=f.label(:buy_sell) %></th>
        <td colspan="2"><%= f.radio_button(:buy_sell, 'buy', :id =>"share-buy") %> Buy
        <%= f.radio_button(:buy_sell, 'sell', :id =>"share-sell") %> Sell
        </td>
    </tr>
    <tr>
		<th><%= f.label(:quantity, "Script Qantity", )%></th>
		<td><%= f.text_field(:quantity, :id=>"share-quantity") %></td>
	</tr>
	<tr>
		<th><%= f.label(:rate, "Script unit price")%></th>
		<td><%= f.text_field(:rate, :id=>"share-rate") %></td>		
	</tr>
	<tr>
		<th><%= f.label(:brokerage, "Brokerage")%></th>
		<td><%= f.text_field(:brokerage, :id=>"share-brokerage", :readonly=>true) %></td>
	</tr>
	<tr>
		<th><%= f.label(:net_rate, "Net rate")%></th>
		<td><%= f.text_field(:net_rate, :id=>"share-net_rate", :readonly=>true) %></td>
	</tr>
	<tr>
		<th><%= f.label(:net_value, "Net Value")%></th>
		<td><%= f.text_field(:net_value,  :id=>"share-net_value", :readonly=>true) %></td>
	</tr>
	<tr>
		<th></th>	
		<th></th>	
	</tr>
</table>

app/views/shares/delete.html.erb
<%= link_to("< Back to Main", {:action => 'index', :share_id =>@share.id}, :class => 'back-link') %>
<div class ="new share">
	<h2> Delete a transaction detail</h2>
	<%= form_for(:share, :url => {:action => 'destroy', :id => @share.id}) do |f| %>
		<p> Are you sure you want to permanently delete this transaction detail</p>
		<p class="reference-name"><%= @share.scrip_name %></p>
		<div class="form-buttons">
			<%= submit_tag("Delete Transaction detail") %>
		</div>
	<% end %>
</div>

app/views/shares/edit.html.erb
<%= link_to("< Back to Main", shares_path, :class => 'back-link') %>
<div class ="new share">
	<h2> Update the transaction details</h2>
	<%= form_for(:share, :url => share_path(@share.id), method: :patch) do |f| %>
		<%= render(:partial => "form", :locals => {:f => f}) %>
		<div class="form-buttons">
			<%= submit_tag("Update Transaction") %>
		</div>
	<% end %>
</div>

app/views/shares/index.html.erb
<% @share_title = "Shares" %>
<div class="shares index">
	<h2> Share </h2> 
	<%= link_to(" Add a transaction details", {:action => 'new'}, :class => 'action new')%>			
	<table class="listing" summary="Share list">
		<tr class="header">
			<th> Scrip Name </th>
			<th> Transaction Date </th>
			<th> Buy/Sell </th>
			<th> Quantity </th>
			<th> Unit Price </th>
			<th> Brokerage </th>
			<th> Net rate </th>
			<th> Net Value </th>
			<th> Bank Balance </th>
			<th> Demat Balance </th>			
		</tr>
		<tr class="<%= cycle('odd', 'even') %>">
			<td>
			<%= search_form_for( @q, url: search_shares_path, html: { method: :post })do |f| %>
			<%= f.collection_select :scrip_name_eq, Share.unique_by_scrip_name,:scrip_name,:scrip_name,include_blank: 'Please select'%></td>	
			<td><%= f.collection_select :transaction_date_eq, Share.unique_by_transaction_date,:transaction_date, :transaction_date,prompt: 'Please select'%></td>
			<td><%= f.select :buy_sell_eq,[:buy,:sell],:include_blank => 'Please select'%></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>		
			<td></td>
			<td></td>
			<td><%=f.submit %></td>				
			<% end %>
		</tr>
		<% @shares.each do |share| %>
		<tr class="<%= cycle('odd', 'even') %>">
			<td><%= share.scrip_name %></td>
			<td><%= share.transaction_date.to_date %></td>	
			<td><%= share.buy_sell %></td>
			<td><%= share.quantity %></td>
			<td><%= share.rate %></td>
			<td><%= share.brokerage %></td>
			<td><%= share.net_rate %></td>	
			<td><%= share.net_value %></td>
			<td><%= share.bank_balance %></td>
			<td><%= share.demat_balance %></td>
			<td class="actions">
				<%= link_to("Show", '#', :class =>'action show') %>
				<%= link_to("Edit", edit_share_path(share.id), :class =>'action edit') %>
				<%= link_to("Delet", share_path(share.id), method: :delete, 'class' =>'action edit')   %>
			</td>
			</tr>
		<% end %>	
	</table>
</div>

app/views/shares/new.html.erb
<%= link_to("< Back to Main", {:action => 'index'}, :class => 'back-link') %>
<div class ="new share">
	<h2> Add a transaction details</h2>
	<%= form_for(:share, :url => {:action => 'create'}) do |f| %>
		<%= render(:partial => "form", :locals => {:f => f}) %>
		<div class="form-buttons">
			<%= submit_tag("Create Entry") %>
		</div>
	<% end %>
</div>

app/views/shares/show.html.erb
<h2> Show </h2>

app/views/users/edit.html.erb
<h1> Edit </h1>

app/views/users/index.html.erb
<% @user_title = "Users" %>
<div class="users index">
	<h2> User </h2> 
	<%= link_to(" Add a transaction details", {:action => 'new'}, :class => 'action new')%>			
	<table class="listing" summary="Share list">
		<tr class="header">
			<th> User ID </th>
			<th> User Name </th>
			<th> Created date </th>
			<th> Password </th>			
		</tr>
		<% @users.each do |user| %>
		<tr class="<%= cycle('odd', 'even') %>">
			<td><%= user.id %></td>	
			<td><%= user.user_name %></td>
			<td><%= user.created_at.to_date %></td>
			<td><%= "*********" %></td>	
			<td class="actions">
		        <%= link_to("View Transactions", {:controller=> 'users',:action =>'index', :user_id => user.id}, :class => 'action show') %>
		        <%= link_to("Show", {:action =>'show', :id => user.id}, :class => 'action show') %>
		        <%= link_to("Edit", {:action => 'edit',:id => user.id}, :class => 'action edit') %>
		        <%= link_to("Delete", {:action => 'destroy',:id => user.id}, :class => 'action delete') %>
      		</td>	
		</tr>		
		<% end %>	
	</table>
</div>

app/views/users/new.html.erb
<h1> New </h1>

app/views/users/show.html.erb
<% @user_title = "Users" %>
<div class="users index">
	<h2> User </h2> 
	<%= link_to(" Add a transaction details", {:action => 'new'}, :class => 'action new')%>			
	<table class="listing" summary="Share list">
		<tr class="header">
			<th> User ID </th>
			<th> User Name </th>
			<th> Created date </th>
			<th> Password </th>			
		</tr>
		<% @users.each do |user| %>
		<tr class="<%= cycle('odd', 'even') %>">
			<td><%= user.id %></td>	
			<td><%= user.user_name %></td>
			<td><%= user.created_at.to_date %></td>
			<td><%= "*********" %></td>	
			<td class="actions">
		        <%= link_to("View Transactions", {:controller=> 'users',:action =>'index', :user_id => user.id}, :class => 'action show') %>
		        <%= link_to("Show", {:action =>'show', :id => user.id}, :class => 'action show') %>
		        <%= link_to("Edit", {:action => 'edit',:id => user.id}, :class => 'action edit') %>
		        <%= link_to("Delete", {:action => 'destroy',:id => user.id}, :class => 'action delete') %>
      		</td>	
		</tr>		
		<% end %>	
	</table>
</div>